# -*- coding: utf-8 -*-
"""Project 1: Portfolio and Strategy Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WkvA7i9LIDZ44--JqWiULH5cT4N9VR49
"""

#importing some data libraries
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

from numpy import info
#Downloading companies comparison data and basis data

ticker1 = "AMD"
ticker2 = "NVDA"
ticker3 = "AAPL"

info1 = yf.Ticker(ticker1).info
info2 = yf.Ticker(ticker2).info
info3 = yf.Ticker(ticker3).info

companyN1 = (info1["longName"])
companyN2 = (info2["longName"])
companyN3 = (info3["longName"])

label1 = (companyN1)
label2 = (companyN2)
label3 = (companyN3)

stock1 = yf.download(ticker1, start="2021-01-01", end="2026-01-01")
stock2 = yf.download(ticker2, start="2021-01-01", end="2026-01-01")
stock3 = yf.download(ticker3, start="2021-01-01", end="2026-01-01")

plt.title("Comparison of stock prices")
plt.xlabel("Date")
plt.ylabel("Opening price")

plt.plot(stock1["High"], label=(label1))
plt.plot(stock2["High"], label=(label2))
plt.plot(stock3["High"], label=(label3))

plt.legend()

#Getting the stock prices dataframes
prices = pd.DataFrame()

prices[ticker1] = stock1["Close"]
prices[ticker2] = stock2["Close"]
prices[ticker3] = stock3["Close"]

prices.head()

prices["AMD_MA25"] = prices[ticker1].rolling(25).mean()
prices.head()

plt.title("AMD Price vs MA25")
plt.xlabel("Date")
plt.ylabel("Price")

plt.plot(prices[ticker1], label=ticker1)
plt.plot(prices["AMD_MA25"], label="MA25")

plt.legend()