# -*- coding: utf-8 -*-
"""Project 1: stock_comparison_dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/156hz4yUu9eWCovaBuaoJd_jFddBWvR8P
"""

#By Emilio Ortiz Cervantes, find me on LinkedIn.

#importing some data libraries
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from numpy import info

#Downloading companies comparison data and creating useful functions

ticker1 = "AMD"
ticker2 = "MSFT"
ticker3 = "AAPL"

info1 = yf.Ticker(ticker1).info
info2 = yf.Ticker(ticker2).info
info3 = yf.Ticker(ticker3).info

companyN1 = (info1["longName"])
companyN2 = (info2["longName"])
companyN3 = (info3["longName"])

label1 = (companyN1)
label2 = (companyN2)
label3 = (companyN3)

stock1 = yf.download(ticker1, start="2021-01-01", end="2026-01-01")
stock2 = yf.download(ticker2, start="2021-01-01", end="2026-01-01")
stock3 = yf.download(ticker3, start="2021-01-01", end="2026-01-01")

plt.title("Comparison of stock prices")
plt.xlabel("Date")
plt.ylabel("Opening price")

desired_data = "Low"
#Options: Open, High, Low, Close, Volume

plt.plot(stock1[desired_data], label=(label1))
plt.plot(stock2[desired_data], label=(label2))
plt.plot(stock3[desired_data], label=(label3))

plt.legend()