# -*- coding: utf-8 -*-
"""Project 3: Portfolio Risk & Return Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kd8rsQJg8JTAzBk0SU2O0sTkCePgUvHq
"""

#By Emilio Ortiz Cervantes, feel free to connect with me on LinkedIn : https://www.linkedin.com/in/emilioortizcervantes/

import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
import numpy as np

#User's data

tickers = ["AAPL", "MSFT", "GOOGL", "AMZN", "TSLA"]

start_date = "2020-01-01"
end_date = "2026-01-01"

custom_weights = [0.20, 0.20, 0.20, 0.20, 0.20]

#The total weight must equal 1

risk_free_rate = 0.04

stock_data = yf.download(tickers, start=start_date, end=end_date, auto_adjust=True)

close_prices = stock_data["Close"]

daily_returns = close_prices.pct_change().dropna()

cumulative_returns = (1 + daily_returns).cumprod() - 1

annualized_returns = daily_returns.mean() * 252

annualized_volatility = daily_returns.std() * np.sqrt(252)

sharpe_ratio = (annualized_returns - risk_free_rate) / annualized_volatility

portfolio_daily_returns = (daily_returns * custom_weights).sum(axis=1)

portfolio_cumulative_returns = (1 + portfolio_daily_returns).cumprod() - 1

portfolio_annualized_return = portfolio_daily_returns.mean() * 252

portfolio_annualized_volatility = portfolio_daily_returns.std() * np.sqrt(252)

portfolio_sharpe_ratio = (portfolio_annualized_return - risk_free_rate) / portfolio_annualized_volatility

portfolio_annualized_return = round(portfolio_annualized_return * 100, 2)

portfolio_annualized_volatility = round(portfolio_annualized_volatility * 100, 2)

portfolio_sharpe_ratio = round(portfolio_sharpe_ratio, 2)

comparison = cumulative_returns.copy()
comparison["Custom Portfolio"] = portfolio_cumulative_returns

best_performer = annualized_returns.idxmax()
worst_performer = annualized_returns.idxmin()

best_return = annualized_returns.max()
worst_return = annualized_returns.min()

#Portfolio results:

print(f"Portfolio returns were considered from {start_date} to {end_date}")

print("The annualized return was: ", portfolio_annualized_return, "%")

print()

print("The annualized volatility was: ", portfolio_annualized_volatility, "%")
print("The sharpe ratio was: ", portfolio_sharpe_ratio)

print()

print(f"The best performing stock was {best_performer}, with a {round(best_return * 100, 3)} %")
print(f"The worst performing stock was {worst_performer}, with a {round(worst_return * 100, 3)} %")

print()

if portfolio_cumulative_returns.iloc[-1] > 0:
    print("The portfolio was profitable over the selected period.")
else:
    print("Portfolio was not profitable over the selected period.")
print()


comparison.plot(figsize=(10,5))

plt.title("Cumulative Returns: Stocks vs Custom Portfolio")
plt.xlabel("Date")
plt.ylabel("Cumulative Return")
plt.grid(True)
plt.legend(title="Asset")
plt.show()

print()
print()

portfolio_cumulative_returns.plot(figsize=(10,5), color="orange")

plt.title("Portfolio Cumulative Returns")
plt.xlabel("Date")
plt.ylabel("Cumulative Return")
plt.grid(True)
plt.show()